name: xspec
channels:
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - pip
  - pip:
    - numpy
    - psutil>=5.8
    - chemparse==0.0.9
    - torch
    - torchvision
    - torchaudio
    - matplotlib
    - h5py