name: xspec
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - ipykernel
  - pip
  - pip:
    - psutil>=5.8
    - scipy
    - matplotlib~=3.3.4
    - chemparse==0.0.9
    - h5py
    - torch
    - torchvision
    - torchaudio
    - svmbir
  - git
  - git+https://bitbucket.org/spekpy/spekpy_release.git#egg=spekpy_release
postBuild: 
  python -m ipykernel install --user --name xspec --display-name "xspec"
